# Generated by Django 5.2.14 on 2026-06-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_availabilityblock_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_document', models.FileField(upload_to='doctor_documents/')),
                ('medical_certificate', models.FileField(upload_to='doctor_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctors.doctorprofile')),
            ],
        ),
    ]
